### PR TITLE
fix: correctly adjust left scroll position in nested scroll container

### LINKED ISSUE #56: Node position not updated correctly during scroll [v3 regression]
Since updating from `2.3.0` to `3.0.6`, in a certain scenario (re-built in codesandbox link below), I observed the following bug:

A sticky node is not moving correctly with its anchor when scrolling horizontally.
Instead, it always stays in the same (initial) position.

I built a minimal repro example here: https://codesandbox.io/s/adoring-star-lqpti

If I'd have to guess, I think that the `calculateWidth` function here is not doing what it should, but I am not able to fix the issue myself:
 https://github.com/signavio/react-stick/blob/689d09b89dabaf0a2be858a40a40a209370213ee/src/Stick.js#L230

### PR DESCRIPTION
**Pull request by frontendphil**
Fixes #56 

I've adjusted the `calculateLeft` method to look for the nearest scroll container. This fixes the reported issue. However, be aware that an absolutely positioned node will most likely overlay the scroll container. This means the node will **not** disappear when the anchor is scrolled away. In order to achieve this, you should use the `transportTo` property of the stick to mount the node inside the scroll container.

### CODE REVIEW

**Comment by frontendphil** [comment]
@tzimmermann can you verify whether this fixes the issue for you?

File: src/StickPortal.js [hunk 1]
```diff
@@ -192,9 +192,33 @@ function calculateLeft(
...
+    return null
+  }
+
+  if (element.nodeName === 'BODY' || element.nodeName === 'HTML') {
+    return null
+  }
+
+  const style = getComputedStyle(element)
+
+  if (style.overflowX === 'auto') {
```
Comment (jfschwarz) [inline src/StickPortal.js:213]: maybe also handle `overflow: scroll`

File: src/StickPortal.js [hunk 2]
```diff
@@ -192,9 +192,33 @@ function calculateLeft(
     return result - hostLeft
   }
 
+  if (scrollHost) {
```
Comment (jfschwarz) [inline src/StickPortal.js:195]: I guess we need the same extra handling for `calculateTop` and horizontal scrolling, too.

File: src/StickPortal.js (hunk 1 above)
Comment (frontendphil) [reply src/StickPortal.js:213]: Ah yeah... I somehow threw that away after I've typed it.

**Comment by tzimmermann** [comment]
> @tzimmermann can you verify whether this fixes the issue for you?

No idea why, but when I test with this branch, I get 

```
react.development.js?38bb:1465 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js?38bb:1465)
    at useState (react.development.js?38bb:1496)
    at Stick (Stick.js?d58c:36)
```

pointing to the first `useState` in `Stick`: https://github.com/signavio/react-stick/blob/301c2e9bcf2121848a07f328663c9a754a0024b7/src/Stick.js#L47

File: src/StickPortal.js (hunk 2 above)
Comment (frontendphil) [reply src/StickPortal.js:195]: Interestingly that doesn't seem to be the case. Look at the regression example at the bottom of the example page. Vertical scroll seems to "just work".

**Comment by frontendphil** [comment]
@tzimmermann you'll need to `yarn link` the `react` and `react-dom` versions of your main application so that there aren't multiple versions of them. 

@jfschwarz I've also snuck in a small performance improvement so that a portal node will only measure its position when the node is actually visible. This should save us quite some CPU cycles.

**Comment by tzimmermann** [comment]
@frontendphil I confirm that the scrolling issue is fixed. I noticed another issue, though, that wasn't there in 2.x: The node "jumps" from the top left corner to its correct position upon opening:
Screen Recording 2020-05-07 at 08 43 26


Do you want me to open a new issue for that?

**Comment by frontendphil** [comment]
@tzimmermann this should now also be fixed. The `node` is only rendered after the initial position has been calculated. That should make this flicker go away.
